### ISSUE TITLE
eslint-plugin-flow-vars is deprecated

### ISSUE THREAD

**Issue by amilajack** [ryyppy/flow-intro#14]
https://github.com/zertosh/eslint-plugin-flow-vars#this-project-is-deprecated

It was merged into [eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype)

Can I make a PR to update this?

**Comment by ryyppy** [comment]
Hey! Sorry for the late response, I messed up my notifications and didn't find this issue right away...
Right now I am super busy with other stuff, so I would be super happy if you submit a PR for that!

**Comment by amilajack** [comment]
Definitely! I'll look into this. Also is it fine if I mention [this plugin](https://github.com/amilajack/eslint-plugin-flowtype-errors) that I'm working on? Personally I think it makes editor/IDE integration much easier.

**Comment by ryyppy** [comment]
Yeah sure, but I never tried it so far, since we try to separate those responsibilities... Maybe add it to the IDE integration part as another alternative for integration?

**Comment by amilajack** [comment]
Will do, thanks!
