### ISSUE TITLE
Lesson 00/03 should use assert.strictEqual

### ISSUE THREAD

**Issue by nwshane** [ryyppy/flow-intro#18]
Tell me if I'm wrong, but I assume that the test at the bottom of the `tutorial/00-basics/03-dynamic-object-keys.js` should fail? At the moment, the test passes because it compares `'1000'` to `1000` using the equal comparison operator rather (`assert.equal`) instead of the strict equality operator (`assert.strictEqual`).

Let me know if this is right and I'll submit a pull request changing this to `assert.strictEqual`.

**Comment by ryyppy** [comment]
Oh yeah, very true... a `strictEqual` would be a better fit in that case :-)
Thanks for pointing this out,.. I would happily accept a PR!

**Comment by nwshane** [comment]
Cool :) thanks for the tutorial!
