### ISSUE TITLE
babel-preset-flow is what the official docs say to install

### ISSUE THREAD

**Issue by rafi** [ryyppy/flow-intro#20]
Official docs instruct to install `babel-preset-flow`, which is a "Babel preset for all Flow plugins." but currently seems to only include `transform-flow-strip-types`.

**Comment by ryyppy** [comment]
Yeah, this part is actually quite old... the installation instructions pre-date the newest doc website...
Currently I have no time in updating it,.. so contributions are very welcome! :-)
