### ISSUE TITLE
Add Flow-Typed in there

### ISSUE THREAD

**Issue by ryyppy** [ryyppy/flow-intro#4]
As soon as https://github.com/flowtyped/flow-typed is officially released as 1.0, I would like to cover the usage of this tool right here too.

**Comment by ryyppy** [comment]
It's also roughly covered in the guidelines found in #11

**Comment by dvakatsiienko** [comment]
Our team started using Flow a week ago, and we are struggling to find relevant information about writing libdefs with flow-typed.
It would be just great to have a tutorial guide!

**Comment by ryyppy** [comment]
Hey :-)

Check out the official docs:
https://flow.org/en/docs/libdefs/creation/

Also here are the contribution guides for flow-typed:
https://github.com/flowtype/flow-typed/blob/master/CONTRIBUTING.md

Does this help?

**Comment by dvakatsiienko** [comment]
@ryyppy Yes! thank you very much! =)
